version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: note
      POSTGRES_PASSWORD: 2222
      POSTGRES_DB: notes
      PGDATA: .src/main/resources/database
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ADMINER_PORT=8081

  notes:
    image: amazoncorretto:21-alpine
    volumes:
      - ./build/libs/simple-0.0.1-SNAPSHOT.jar:/app/simple-0.0.1-SNAPSHOT.jar
    working_dir: /app
    command: [ "java", "-jar", "simple-0.0.1-SNAPSHOT.jar" ]
    ports:
      - "8080:8080"
    restart: always

networks:
  default:
    external:
      name: bridge