name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose services
        run: docker-compose up -d

      # Add additional steps here, such as testing your services or deploying

      - name: Stop Docker Compose services
        run: docker-compose down
